---
title: "Fix the code"
author: "Vinicius Rodrigues"
date: "2024-01-02"
output: html_document
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
```
# Preparação para o exercício:

Carregue o _data frame_ _mtcars_

```{r, include=T, eval=F}
data(mtcars)
```

## Encontre os erros nos exemplos abaixo:

**Exemplo 1**

```{r, include=T, eval=F}
Head(mtcars)
```

**Exemplo 2**

```{r, include=T, eval=F}
dim[mtcars]
```

**Exemplo 3**

```{r, include=T, eval=F}
nomes(mtcars)
```

**Exemplo 4**

```{r, include=T, eval=F}
str(Mtcars)
```

**Exemplo 5**

```{r, include=T, eval=F}
head(mtcars, x = 8)
```

**Exemplo 6**

```{r, include=T, eval=F}
v1 <- ("branco", "preto", "roxo", "abobora")
```

**Exemplo 7** 

```{r, include=T, eval=F}
v2 <- c("1", "2", "3", "4")
v1 + 42
```

**Exemplo 8**

```{r, include=T, eval=F}
v1 <- c("branco", "preto", "roxo", "abobora"
```

**Exemplo 9**

```{r, include=T, eval=F}
v3 <- c(33 31 40 25 27 40)
```

**Exemplo 10**

```{r, include=T, eval=F}
v1 <- c(branco, preto, roxo, abobora)
```

**Exemplo 11**

```{r, include=T, eval=F}
v1 <- c("branco" "preto" "roxo" "abobora")
```

**Exemplo 12**

```{r, include=T, eval=F}
v3 <- C(33, 31, 40, 25, 27, 40)
```

**Exemplo 13**

```{r, include=T, eval=F}
v1 <- c("branco", "preto"", "roxo", "abobora")
v3 <- c(33, 31, 40, 25, 27, 40)
myData <- data.frame(v1, v3)
```

**Exemplo 14**

```{r, include=T, eval=F}
v1 <- c("branco", "preto"", "roxo", "abobora")
v4 <- c(12, 100, 50, 5)
myData <- data.frame(v1 = cor, v4 = quantidade)
```

**Exemplo 15**

```{r, include=T, eval=F}
ls
```

**Exemplo 16**

```{r, include=T, eval=F}
v1 <- c("branco", "preto", "roxo", "abobora")
sum(v1)
```

**Exemplo 17**

```{r, include=T, eval=F}
i <- c(10,30,40)
meus_dados <- c(1,2, "números ", i)

rm("numeros")
```

**Exemplo 18**

```{r, include=T, eval=F}

meus_dados <- c(10,20,30,40,50,60,
                70,80,90,100,110,
                120,130,140,150,160,
                170,180,190,200,210
                220,230,240,250,260,
                270,280,290,300,310,
                320,330,340,350,360)
                
```

