---
title: "Encontro 1"
author: "Vinicius Rodrigues"
date: "2023-12-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introdução à programação em R (fev-24)

## Encontro 1 - Preparação do ambiente computacional: R e RStudio.
Neste primeiro encontro, o principal objetivo é desmistificar o ato de programar. Demonstrar que aquela sequência enorme de linhas com texto em cor verde são, em grande parte, uma estética descolada e inofensiva. (Tente ir na barra de menu do R Studio: Tools > Global Options > Apparence > Editor Theme)

O substantivo "linguagem" não é sem motivo: como em qualquer idioma, quando se conhece a estrutura de funcionamento, você pode decifrar, compreender e traduzir o que aparecer - não importa a quantidade de linhas que apareça na sua frente! 

Quero que tenham isso em mente e fiquem completamente tranquilas e tranquilos quanto ao aprendizado. Vocês saberão programar em R ao final do curso. Evidentemente, isso não significa que terão fluência na "língua" R, mas saberão do que se trata, poderão fazer seus programas e caminhar com as próprias pernas para aprimorar suas habilidades (nesta ou em qualquer outra linguagem de programação).

### Roteiro para a aula
1. Questões burocráticas, apresentação do curso, discussão do programa e survey da turma.

2. Em seguida, apresento o ambiente computacional do R e do RStudio [Tutorial 1](https://rpubs.com/vinrodr/tutorial_1_introR)

3. Por fim, mãos à obra: o básico da linguagem R. O [Tutorial 2](https://rpubs.com/vinrodr/tutorial_2_introR) traz conceitos básicos da linguagem, antes de avançarmos em soluções e código propriamente. 

4. O próximo encontro será mais fácil, pois os nomes e conceitos ditos em abstrato serão vistos na prática da programação. Mas antes de finalizar, façam o exercício de fixação abaixo. A proposta é trazer os erros mais comuns para que vocês corrijam. Não se engane: embora sejam bem simples, acontecem muito! [Fix the code](https://rpubs.com/vinrodr/fixthecode_intror)

### Extra-classe
Como o desenho do curso é intensivo, não haverá muito tempo para que vocês leiam o material da bibliografia. Não espero que façam agora, mas tenham em mente que o aprimoramento será muito mais fácil caso leiam. 
Fazendo uma analogia, encarem a bibliografia como manuais de uma máquina que você adquiriu. Você pode até conseguir fazer funcionar sozinho, mas ler o manual lhe habilita ao uso otimizado. Cada obra trará exemplos de código e sugestões de aplicação para uma ou várias bibliotecas do R.

### Recursos para aprimoramento e fixação
* [Curso de introdução do Datacamp](https://www.datacamp.com/courses/free-introduction-to-r): Curso de nivelamento para oficinas de R do datacamp. É o que vocês verão nos dois primeiros encontros do nosso curso.
* [Applied Data Science Training](https://www.uscspec.org/applied-data-science-trainings) - Em Inglês: Aulas, tutoriais e exercícios do Laboratório de Segurança e Política Econômica da University of Southern California (USC-SPEC Lab), voltados ao aprendizado autônomo de gerenciamento e visualização de dados em R.